# Generated by Django 3.0.3 on 2020-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colours',
            name='colourcode',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
