# Generated by Django 3.0.3 on 2020-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200827_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colours',
            name='colourcode',
            field=models.CharField(default='RAL', max_length=10),
        ),
    ]
