# Generated by Django 3.0.3 on 2020-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modifiedby',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
