# Generated by Django 3.0.3 on 2020-09-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_historicalproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='modifiedby',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modifiedby',
        ),
    ]
