# Generated by Django 3.0.3 on 2020-09-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200902_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='modifiedby',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='modifiedby',
            field=models.CharField(max_length=20),
        ),
    ]
