# Generated by Django 2.2.13 on 2020-09-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200902_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='minquantity',
            field=models.IntegerField(default='50'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minquantity',
            field=models.IntegerField(default='50'),
        ),
    ]
